import { Group, Member, Invoice } from '../types';

export const mockMembers: Member[] = [
  {
    id: 'm1',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    avatar: 'SC',
    color: '#3b82f6',
  },
  {
    id: 'm2',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    avatar: 'AJ',
    color: '#8b5cf6',
  },
  {
    id: 'm3',
    name: 'Maria Garcia',
    email: 'maria@example.com',
    avatar: 'MG',
    color: '#ec4899',
  },
  {
    id: 'm4',
    name: 'James Smith',
    email: 'james@example.com',
    avatar: 'JS',
    color: '#10b981',
  },
  {
    id: 'm5',
    name: 'Emily Davis',
    email: 'emily@example.com',
    avatar: 'ED',
    color: '#f59e0b',
  },
];

export const mockGroups: Group[] = [
  {
    id: 'g1',
    name: 'NYC Trip 2026',
    members: [mockMembers[0], mockMembers[1], mockMembers[2]],
    totalExpense: 2847.35,
    pendingBalance: 450.0,
    createdAt: new Date('2026-01-15'),
  },
  {
    id: 'g2',
    name: 'Office Team Lunch',
    members: [mockMembers[0], mockMembers[1], mockMembers[3], mockMembers[4]],
    totalExpense: 523.8,
    pendingBalance: 120.5,
    createdAt: new Date('2026-01-20'),
  },
  {
    id: 'g3',
    name: 'Apartment Utilities',
    members: [mockMembers[2], mockMembers[3]],
    totalExpense: 1245.0,
    pendingBalance: 0,
    createdAt: new Date('2026-01-10'),
  },
  {
    id: 'g4',
    name: 'Weekend Getaway',
    members: [mockMembers[0], mockMembers[2], mockMembers[4]],
    totalExpense: 1892.5,
    pendingBalance: 245.75,
    createdAt: new Date('2026-01-22'),
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv1',
    groupId: 'g1',
    name: 'Hotel Stay - Times Square',
    merchant: 'Marriott Hotels',
    date: new Date('2026-01-16'),
    total: 1245.0,
    status: 'reviewed',
    items: [
      { id: 'i1', name: 'Room 3 nights', quantity: 3, price: 415.0 },
      { id: 'i2', name: 'Breakfast buffet', quantity: 6, price: 180.0 },
    ],
    uploadedBy: 'm1',
    createdAt: new Date('2026-01-16'),
  },
  {
    id: 'inv2',
    groupId: 'g1',
    name: 'Dinner at Italian Restaurant',
    merchant: "Carbone's NYC",
    date: new Date('2026-01-17'),
    total: 482.35,
    status: 'needs-review',
    items: [
      { id: 'i3', name: 'Pasta dishes', quantity: 3, price: 195.0 },
      { id: 'i4', name: 'Appetizers', quantity: 2, price: 68.0 },
      { id: 'i5', name: 'Wine', quantity: 2, price: 156.0 },
      { id: 'i6', name: 'Desserts', quantity: 3, price: 45.0 },
      { id: 'i7', name: 'Tax & Tip', quantity: 1, price: 18.35 },
    ],
    uploadedBy: 'm2',
    createdAt: new Date('2026-01-17'),
  },
  {
    id: 'inv3',
    groupId: 'g1',
    name: 'Broadway Show Tickets',
    merchant: 'Ticketmaster',
    date: new Date('2026-01-18'),
    total: 720.0,
    status: 'reviewed',
    items: [{ id: 'i8', name: 'Orchestra seats', quantity: 3, price: 240.0 }],
    uploadedBy: 'm1',
    createdAt: new Date('2026-01-18'),
  },
  {
    id: 'inv4',
    groupId: 'g2',
    name: 'Team Lunch - Thai Food',
    merchant: 'Bangkok Kitchen',
    date: new Date('2026-01-21'),
    total: 523.8,
    status: 'reviewed',
    items: [
      { id: 'i9', name: 'Main dishes', quantity: 4, price: 88.0 },
      { id: 'i10', name: 'Appetizers', quantity: 3, price: 45.0 },
      { id: 'i11', name: 'Drinks', quantity: 4, price: 28.0 },
      { id: 'i12', name: 'Tax & Tip', quantity: 1, price: 10.8 },
    ],
    uploadedBy: 'm1',
    createdAt: new Date('2026-01-21'),
  },
];
